In [16]:
import pandas as pd 

df = pd.read_csv('..\data\Sales_Data_2024_2025.csv')

In [17]:
df.count()

Order ID         5000
Order Date       5000
Customer Name    5000
Region           5000
City             5000
Category         5000
Sub-Category     5000
Product Name     5000
Quantity         5000
Unit Price       5000
Discount         5000
Sales            5000
Profit           5000
Payment Mode     5000
dtype: int64

In [18]:
df.isnull().sum()

Order ID         0
Order Date       0
Customer Name    0
Region           0
City             0
Category         0
Sub-Category     0
Product Name     0
Quantity         0
Unit Price       0
Discount         0
Sales            0
Profit           0
Payment Mode     0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df['Order ID'].nunique()
df['Category'].nunique()
df['Product Name'].nunique()
df['Sub-Category'].value_counts()

Sub-Category
Sofa             122
Football         120
Women's Wear     118
Bed              117
Lamp             117
Biography        116
Cookware Set     116
Juicer           115
Non-Fiction      114
Vase             114
Refrigerator     107
Tennis Racket    106
Face Cream       102
RC Car           101
Fiction          101
Kids Wear        100
Textbook         100
Action Figure    100
Wall Art         100
Men's Wear       100
Yoga Mat          99
Cabinet           99
Shoes             98
Spices            97
Smartwatch        97
Dumbbells         97
Comics            97
Sugar             97
Headphones        96
Board Game        96
Microwave         96
Chair             95
Accessories       95
Lipstick          95
Rice              94
Table             94
Puzzle            94
Camera            94
Mixer Grinder     94
Mobile            94
Oil               93
Clock             93
Foundation        92
Laptop            91
Cushion           91
Wheat             89
Cricket Bat       89
Doll              87
Shampoo           87
Perfume           84
Name: count, dtype: int64

In [21]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Order Date'].min()
df['Order Date'].max()

Timestamp('2025-10-03 00:00:00')

In [22]:
(df['Sales']<0).sum()
(df['Profit']<0).sum()
(df['Discount']<0).sum()
df['Discount'].value_counts().sort_index()
(df['Quantity']<0).sum()

np.int64(0)

In [23]:
df[['Quantity', 'Unit Price', 'Discount', 'Sales', 'Profit']].head(10)

   Quantity  Unit Price  Discount      Sales    Profit
0         2       36294         5   68958.60  10525.09
1         1       42165        20   33732.00   6299.66
2         4       64876        20  207603.20  19850.27
3         5       37320        15  158610.00  36311.02
4         1       50037        10   45033.30   9050.04
5         5       40287        15  171219.75  23722.84
6         2        3636         5    6908.40    680.26
7         1       15885        10   14296.50   1289.03
8         1       40834        20   32667.20   3700.89
9         2       16686        15   28366.20   5703.09

In [24]:
df['Order Month'] = df['Order Date'].dt.to_period('M')
df['Profit Margin'] = (df['Profit']/df['Sales'])*100 
df['Profit Margin'] = df['Profit Margin'].round(2)

In [25]:
df.columns

Index(['Order ID', 'Order Date', 'Customer Name', 'Region', 'City', 'Category',
       'Sub-Category', 'Product Name', 'Quantity', 'Unit Price', 'Discount',
       'Sales', 'Profit', 'Payment Mode', 'Order Month', 'Profit Margin'],
      dtype='str')

In [26]:
df.drop_duplicates()

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode,Order Month,Profit Margin
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294,5,68958.6,10525.09,Debit Card,2024-10,15.26
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165,20,33732.0,6299.66,Debit Card,2025-08,18.68
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876,20,207603.2,19850.27,Credit Card,2023-11,9.56
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320,15,158610.0,36311.02,UPI,2025-05,22.89
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037,10,45033.3,9050.04,Debit Card,2025-01,20.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,14996,2024-06-25,Nishith Kulkarni,East,Kolkata,Books,Fiction,Fiction Veritatis,3,60671,0,182013.0,11853.15,Debit Card,2024-06,6.51
4996,14997,2024-12-22,Aaina Chander,North,Jaipur,Toys,Doll,Doll Nulla,5,70048,0,350240.0,31237.23,Credit Card,2024-12,8.92
4997,14998,2025-04-15,Dhanush Gara,South,Bangalore,Beauty,Lipstick,Lipstick Eaque,1,42162,15,35837.7,7827.50,Debit Card,2025-04,21.84
4998,14999,2024-07-08,Divyansh Malhotra,East,Kolkata,Electronics,Smartwatch,Smartwatch Adipisci,4,13568,10,48844.8,6603.86,Credit Card,2024-07,13.52
4999,15000,2024-02-04,Aarush Walla,West,Goa,Clothing,Kids Wear,Kids Wear Repellat,1,76762,10,69085.8,5785.85,Net Banking,2024-02,8.37

In [27]:
df.to_csv('..\data\cleaned_sales_data.csv')

In [29]:
df[['Sales','Profit']].describe()

               Sales        Profit
count    5000.000000   5000.000000
mean   106733.204870  15941.746982
std     85108.208202  14897.684916
min       264.100000     19.120000
25%     39766.537500   4892.295000
50%     83080.325000  11108.525000
75%    156968.587500  22467.987500
max    398485.000000  89688.440000

In [ ]:
df.head()

,Order ID,Order Date,Customer Name,Region,City,Category,Sub-Category,Product Name,Quantity,Unit Price,Discount,Sales,Profit,Payment Mode,Order Month,Profit Margin
0,10001,2024-10-19,Kashvi Varty,South,Bangalore,Books,Non-Fiction,Non-Fiction Ipsum,2,36294,5,68958.6,10525.09,Debit Card,2024-10,15.26
1,10002,2025-08-30,Advik Desai,North,Delhi,Groceries,Rice,Rice Nemo,1,42165,20,33732.0,6299.66,Debit Card,2025-08,18.68
2,10003,2023-11-04,Rhea Kalla,East,Patna,Kitchen,Juicer,Juicer Odio,4,64876,20,207603.2,19850.27,Credit Card,2023-11,9.56
3,10004,2025-05-23,Anika Sen,East,Kolkata,Groceries,Oil,Oil Doloribus,5,37320,15,158610.0,36311.02,UPI,2025-05,22.89
4,10005,2025-01-19,Akarsh Kaul,West,Pune,Clothing,Kids Wear,Kids Wear Quo,1,50037,10,45033.3,9050.04,Debit Card,2025-01,20.10